# Generated by Django 5.2 on 2025-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_form_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='organizer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
