# Generated by Django 5.2 on 2025-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name', max_length=100)),
                ('date', models.CharField(help_text='Event date')),
                ('time', models.CharField(help_text='Event time')),
                ('venue', models.CharField(help_text='Event venue', max_length=200)),
            ],
        ),
    ]
