# Generated by Django 5.2 on 2025-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_form_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('meal_time', models.CharField(max_length=10)),
                ('items', models.TextField()),
            ],
        ),
    ]
