# Generated by Django 5.2 on 2025-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('meal_type', models.CharField(max_length=20)),
                ('menu', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
