# Generated by Django 5.2 on 2025-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_availableroom_alter_allocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
