# Generated by Django 5.2 on 2025-04-07 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_floors', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('four', '4 Sharing'), ('double', 'Double Sharing'), ('single', 'Single Seater')], max_length=10)),
                ('ac_type', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('total_beds', models.PositiveIntegerField()),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostels.room')),
            ],
        ),
    ]
