# Generated by Django 5.2 on 2025-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostels', '0003_complaintmaintenance_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('user',), name='unique_active_allocation_per_user'),
        ),
    ]
