# Generated by Django 5.2 on 2025-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_messmenu_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together={('day', 'meal_type')},
        ),
    ]
