# Generated by Django 5.2 on 2025-04-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_founditem_lostitem_claimrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='founditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='messmenu',
            options={'ordering': ['day', 'meal_type']},
        ),
    ]
